name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 

- name: Publish Docker Action
  # You may pin to the exact commit or the version.
  # uses: jerray/publish-docker-action@87d84711629b0dc9f6bb127b568413cc92a2088e
  uses: jerray/publish-docker-action@v1.0.5
  with:
    # Username used to login docker registry
    username: ${{ secrets.DOCKER_HUB_USERNAME }}
    # Password used to login docker registry
    password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    # Docker registry server address
